### ISSUE TITLE
Cannot generate correct sized tiles

### ISSUE THREAD

**Issue by Chaimera-Baeddel** [paradrogue/Godot-QuickTileset#2]
I am attempting to use this, using one of the tilesets linked in the readme (https://www.kenney.nl/assets/bit-pack). They are 16x16 tiles. When it auto detects the size, it assumes they are 64x64. When I disabled that and manually set them, setting any value other than the correct ones (for example, 32x16, 64x32, even odd ones like 17x16) generates tiles, though of the wrong size obviously, but whenever I set it to 16x16 it simply does not generate them at that size, keeping them at whatever they were last generated as.

**Comment by Chaimera-Baeddel** [comment]
I managed to get it working with one of the images that has space between each tile, with setting the padding, but it does not work for the packed versions of any of the images, without that padding.

**Comment by bluematt** [comment]
Thanks for the issue.  I downloaded the Kenney asset pack you mention, and think there may be a couple of issues you're experiencing:

1. The filenames (by default) don't specify size (e.g. `16x16`) so won't be recognised as containing tiles of that size.  This will need to be set manually, or rename the file so that it ends with `_16x16`, or similar.

2. There is a *soft* limit of 1024 tiles being auto-generated by default—this is for performance reasons.  These tilesets contain slightly more tiles than this (1078), so are not imported (there is a warning to this effect in the Output console—see below).  You can disable this limit by selecting the "Ignore tile limits" option in the `QuickTileset` node, which will allow the tiles to be imported.

```
 modules/gdscript/gdscript_functions.cpp:789 - QuickTileset: A large number (1078) of tiles will be created.  This may cause performance issues.
 modules/gdscript/gdscript_functions.cpp:789 - QuickTileset: The tile limit (1024) has prevented the TileSet from being generated. Aborting.
```

**Comment by Chaimera-Baeddel** [comment]
Ignoring tile limits made it work, thank you! I miscalculated how many tiles there were in it so I thought I was under 1024 and thus didn't try that option.

**Comment by bluematt** [comment]
Thanks for letting me know. 👍
